adding timestamp and address fields to many events
HausDAO/daohaus-monorepo pull request #468
Opened 2022-07-18 22:47 UTC by brossetti1

## GitHub Issue

fixes https://github.com/HausDAO/daohaus-monorepo/issues/238

## Changes

adding several timestamp and address details to Dao, Proposals, Votes, and Member

includes build files

## Packages Added

N/A

## Checks

Before making your PR, please check the following:

- [X] Critical lint errors are resolved
- [X] App runs locally
- [X] App builds locally (run the build command for *any impacted package* and check for any errors before the PR)

2022-07-18 22:50 UTC, brossetti1 commented
@skuhlmann i noticed Dao already had `transactionHashSummon` so skipped `summonTxHash`

wondering if we need to update fields in:

transformProposal : https://github.com/HausDAO/daohaus-monorepo/blob/develop/libs/dao-data/src/utils/transformers.ts#L15
transformMembershipList: https://github.com/HausDAO/daohaus-monorepo/blob/develop/libs/dao-data/src/utils/transformers.ts#L56

2022-07-19 02:28 UTC, skuhlmann requested changes

2022-07-19 02:28 UTC, skuhlmann commented on apps/v3-subgraph/schema.graphql
> +  proposalSponsorTxHash: Bytes!
This should probably be nullable as we won't have data for that field when saving the proposal upon submission.

2022-07-19 02:28 UTC, skuhlmann commented on apps/v3-subgraph/schema.graphql
> +  proposalSponsorTxAt: BigInt!
nullable

2022-07-19 02:28 UTC, skuhlmann commented on apps/v3-subgraph/schema.graphql
> +  proposalCancelTxHash: Bytes!
same with these - all the proposal states that might not happen or don't happen until later in the proposal lifecycle will need to be nullable.

sponsor
cancelled
processed

2022-07-19 02:28 UTC, skuhlmann commented on apps/v3-subgraph/schema.graphql
> +  lastDelegateUpdateTxHash: Bytes!
nullable

2022-07-20 19:36 UTC, skuhlmann approved these changes

2022-07-20 19:36 UTC, merged