Corrections
HausDAO/daohaus-monorepo pull request #950
Opened 2022-10-05 22:59 UTC by jordanlesich

## GitHub Issue

Corrections we made during Wednesday's testing session

## Changes

See commits

## Packages Added

## Checks

Before making your PR, please check the following:

- [x] Critical lint errors are resolved
- [x] App runs locally
- [x] App builds locally (run the build command for *any impacted package* and check for any errors before the PR)

2022-10-06 20:16 UTC, santteegt requested changes

2022-10-06 20:16 UTC, santteegt commented on apps/core-app/src/components/MetadataSettings.tsx
> +          {console.log(dao.tags)}
clean console.log

2022-10-07 19:35 UTC, earth2travis approved these changes
Beautiful

2022-10-07 19:35 UTC, earth2travis approved these changes

2022-10-07 19:36 UTC, earth2travis approved these changes

2022-10-07 19:37 UTC, merged